### ISSUE TITLE
2025.6.0 - WeatherLink Integration Requires Update

### ISSUE THREAD

**Issue by NRutt2005** [siku2/hass-weatherlink#65]
I updated to the 2025.6.0 Home Assistant OS and it is now not loading the WeatherLink Integration.

It worked fine on the 2025.05 version with no issues. 

Here is the log for the WeatherLink Error I’m receiving.

![Image](https://github.com/user-attachments/assets/1458e1ad-a026-4504-ae4d-0117d0426998)

To fix this issue, in the the __init__.py file, remove 167 thru 170 in the original code and add the following  below on line 167.

await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)

This adding this line of code solved the issue.

**Comment by antamuk** [comment]
Just to add that this is also an issue with my HAOS installation upon upgrade to 2025.6.0.  with the same error: 

```
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/weatherlink/__init__.py", line 169, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, platform)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?`
```

Will wait for update, thanks.

**Comment by siku2** [comment]
This specific issue was resolved in the latest release.

**Comment by dazimmermann** [comment]
siku2, I'm already running WeatherLink 0.5.3 with OS 6.1.  Are you saying this should be fixed with that version of WeatherLink?  Is the problem that I need to re-add the HACS repository?

**Comment by dazimmermann** [comment]
Thanks.  Latest WeatherLink update has resolved the issue for me.
