### ISSUE TITLE
Weatherlink Integration gets startup error since may 2025 version tested with current version 2025.6.3

### ISSUE THREAD

**Issue by SteveHoyt** [siku2/hass-weatherlink#72]
The integration fails since the May 2025 version . 

Error setting up entry WeatherLink 001D0A710F5F for weatherlink

Debug log included using latest version 2025.3

2025-06-26 13:43:28.729 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration eero which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-06-26 13:43:28.732 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration weatherlink which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-06-26 13:43:28.735 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ha_carrier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-06-26 13:43:28.737 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration mass which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-06-26 13:43:28.739 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration isy994 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-06-26 13:43:28.741 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-06-26 13:43:28.744 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-06-26 13:43:40.592 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry WeatherLink 001D0A710F5F for weatherlink
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/weatherlink/__init__.py", line 169, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, platform)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
2025-06-26 13:43:40.639 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Outside Airlink for weatherlink
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/weatherlink/__init__.py", line 169, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, platform)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
2025-06-26 13:43:40.876 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Inside Airlink for weatherlink
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/weatherlink/__init__.py", line 169, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, platform)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
2025-06-26 13:43:41.687 WARNING (SyncWorker_4) [homeassistant.components.rachio.device] Not adding controller 'Linda/Ed’s Rachio-FDDBCE', only controllers owned by 'stevehoyt@comcast.net' may be added
2025-06-26 13:43:45.968 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/__init__.py:2: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  __import__('pkg_resources').declare_namespace(__name__)

2025-06-26 13:43:48.222 ERROR (MainThread) [homeassistant.components.solaredge] Could not retrieve details from SolarEdge API
2025-06-26 13:43:49.618 DEBUG (SyncWorker_5) [nuheat.api] Creating NuHeat session
2025-06-26 13:43:49.622 DEBUG (SyncWorker_7) [nuheat.api] Creating NuHeat session
2025-06-26 13:43:57.058 WARNING (ImportExecutor_0) [homeassistant.const] POWER_VOLT_AMPERE_REACTIVE was used from isy994, this is a deprecated constant which will be removed in HA Core 2025.9. Use UnitOfReactivePower.VOLT_AMPERE_REACTIVE instead, please report it to the author of the 'isy994' custom integration
2025-06-26 13:43:57.067 WARNING (ImportExecutor_0) [homeassistant.const] STATE_LOCKED was used from isy994, this is a deprecated constant which will be removed in HA Core 2025.10. Use LockState.LOCKED instead, please report it to the author of the 'isy994' custom integration
2025-06-26 13:43:57.078 WARNING (ImportExecutor_0) [homeassistant.const] STATE_UNLOCKED was used from isy994, this is a deprecated constant which will be removed in HA Core 2025.10. Use LockState.UNLOCKED instead, please report it to the author of the 'isy994' custom integration
2025-06-26 13:43:57.263 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/pyisyox/node_servers.py", line 277, in get_node_server_profiles
    self.parse_profile(profile)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyisyox/node_servers.py", line 289, in parse_profile
    file_name = file[ATTR_FILE][TAG_NAME]
                ~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
2025-06-26 13:44:05.297 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.29.5 is exactly one major version older than the runtime version 6.31.1 at api.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-06-26 13:44:05.304 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.29.5 is exactly one major version older than the runtime version 6.31.1 at api_options.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-06-26 13:44:09.581 ERROR (MainThread) [pyisyox] Could not communicate with device: 39 8A 28 1
2025-06-26 13:44:09.589 ERROR (MainThread) [pyisyox] Could not communicate with device: 54 79 AC 1
2025-06-26 13:44:09.599 ERROR (MainThread) [pyisyox] Could not communicate with device: 12 74 F3 1
2025-06-26 13:44:09.607 ERROR (MainThread) [pyisyox] Could not communicate with device: 70 29 21 1
2025-06-26 13:44:09.616 ERROR (MainThread) [pyisyox] Could not communicate with device: 15 2D D3 1
2025-06-26 13:44:09.624 ERROR (MainThread) [pyisyox] Could not communicate with device: 15 2E FA 1
2025-06-26 13:44:09.633 ERROR (MainThread) [pyisyox] Could not communicate with device: 15 2F C0 1
2025-06-26 13:44:09.641 ERROR (MainThread) [pyisyox] Could not communicate with device: 12 31 7B 1
2025-06-26 13:44:18.600 ERROR (MainThread) [homeassistant.components.solaredge] Could not retrieve details from SolarEdge API
2025-06-26 13:44:29.125 ERROR (MainThread) [homeassistant.components.solaredge] Could not retrieve details from SolarEdge API
2025-06-26 13:44:30.300 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/ProtocolMessage.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-06-26 13:44:30.396 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/AudioFadeMessage.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-06-26 13:44:30.453 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/PlayerPath.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-06-26 13:44:30.536 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/Origin.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-06-26 13:44:30.612 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/DeviceInfoMessage.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-06-26 13:44:30.660 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/Common.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-06-26 13:44:30.700 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/NowPlayingClient.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-06-26 13:44:30.727 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/NowPlayingPlayer.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-06-26 13:44:30.762 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/AudioFadeResponseMessage.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-06-26 13:44:30.799 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/ClientUpdatesConfigMessage.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-06-26 13:44:30.825 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/ConfigureConnectionMessage.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-06-26 13:44:30.847 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/CryptoPairingMessage.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-06-26 13:44:30.874 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/GenericMessage.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-06-26 13:44:30.904 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/GetKeyboardSessionMessage.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-06-26 13:44:30.926 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/GetRemoteTextInputSessionMessage.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-06-26 13:44:30.966 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/GetVolumeMessage.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-06-26 13:44:30.996 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/GetVolumeResultMessage.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-06-26 13:44:31.041 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/KeyboardMessage.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-06-26 13:44:33.596 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.red_house_net_usage (<class 'custom_components.nodered.sensor.NodeRedSensor'>) is using state class 'measurement' which is impossible considering device class ('energy') it is using; expected None or one of 'total_increasing', 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/zachowj/hass-node-red/issues
2025-06-26 13:44:33.598 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.storeedge_chart_power (<class 'custom_components.nodered.sensor.NodeRedSensor'>) is using state class 'measurement' which is impossible considering device class ('energy') it is using; expected None or one of 'total_increasing', 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/zachowj/hass-node-red/issues
2025-06-26 13:44:50.644 ERROR (MainThread) [homeassistant.components.solaredge] Could not retrieve details from SolarEdge API
2025-06-26 13:45:08.687 WARNING (MainThread) [ring_doorbell.doorbot] Your Ring account does not have an active subscription.
2025-06-26 13:45:31.548 ERROR (MainThread) [homeassistant.components.solaredge] Could not retrieve details from SolarEdge API
2025-06-26 13:45:38.169 ERROR (MainThread) [homeassistant.components.sense.coordinator] Timeout retrieving data: API websocket timed out
2025-06-26 13:46:01.950 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Outside Airlink for weatherlink
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/weatherlink/__init__.py", line 169, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, platform)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
2025-06-26 13:46:14.998 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'weatherlink' sets option flow config_entry explicitly, which is deprecated at custom_components/weatherlink/config_flow.py, line 108: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/siku2/hass-weatherlink/issues
2025-06-26 13:46:52.519 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/stringcase.py:247: SyntaxWarning: invalid escape sequence '\W'
  return re.sub("\W+", "", string)

2025-06-26 13:47:10.106 ERROR (MainThread) [homeassistant.components.sense.coordinator] Timeout retrieving data: API websocket timed out
2025-06-26 13:48:11.993 WARNING (MainThread) [ring_doorbell.doorbot] Your Ring account does not have an active subscription.
2025-06-26 13:49:22.348 DEBUG (MainThread) [custom_components.weatherlink] received broadcast conditions
2025-06-26 13:51:02.783 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry WeatherLink 001D0A710F5F for weatherlink
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/weatherlink/__init__.py", line 169, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, platform)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
2025-06-26 13:51:02.799 ERROR (MainThread) [custom_components.weatherlink] failed to start broadcast
Traceback (most recent call last):
  File "/config/custom_components/weatherlink/__init__.py", line 124, in __broadcast_loop
    broadcast = await WeatherLinkBroadcast.start(self.session)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/weatherlink/api/broadcast.py", line 165, in start
    protocol = await Protocol.open(
               ^^^^^^^^^^^^^^^^^^^^
        renewer.remote_addr, addr="0.0.0.0", port=renewer.broadcast_port
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/weatherlink/api/broadcast.py", line 35, in open
    _, protocol = await loop.create_datagram_endpoint(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 1461, in create_datagram_endpoint
    raise exceptions[0]
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 1445, in create_datagram_endpoint
    sock.bind(local_address)
    ~~~~~~~~~^^^^^^^^^^^^^^^
OSError: [Errno 98] Address in use
2025-06-26 13:51:14.987 WARNING (MainThread) [ring_doorbell.doorbot] Your Ring account does not have an active subscription.
2025-06-26 13:51:44.851 DEBUG (MainThread) [custom_components.weatherlink] received broadcast conditions
